name: ci-pipeline
on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Lint (dotnet format)
        run: |
          dotnet format \
            --verify-no-changes \
            --verbosity diagnostic
